In [4]:
import numpy as np

# make ndarray (numpy array
# )
arr= np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [6]:
# make 2d array
tow_d = np.array([[1, 2, 3], [10, 9, 8]])
print(tow_d)
print(tow_d[0][0])

[[ 1  2  3]
 [10  9  8]]
1


In [14]:
three_d = np.array([
    [
        [1, 2, 3], [212, 23134, 7675], [122, 4212, 12312]
    ],
    [
        [1, 2, 3], [212, 23134, 7675], [122, 4212, 12312]
    ]
    
])

three_d[1][2][1]

4212