In [32]:
import numpy as np

# make ndarray (numpy array
# )
arr= np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [33]:
# make 2d array
tow_d = np.array([[1, 2, 3], [10, 9, 8]])
print(tow_d)
print(tow_d[0][0])

[[ 1  2  3]
 [10  9  8]]
1


In [34]:
three_d = np.array([
    [
        [1, 2, 3], [212, 23134, 7675], [122, 4212, 12312]
    ],
    [
        [1, 2, 3], [212, 23134, 7675], [122, 4212, 12312]
    ]
    
])

three_d[1][2][1]

4212

# check number of dimensions 

In [35]:

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [36]:
# set number of dimension

arr = np.array([1, 2, 3], ndmin=3)

three_d = np.array(
    [
        [
            [2, 2, 1],
            [2, 2, 8]
        ],
        [
            [2, 2, 1],
            [2, 2, 8]
        ],   [
            [2, 2, 1],
            [2, 2, 8]
        ]
    ]
)

print(three_d.ndim)
print(arr)
print(three_d[1][0][-1]) # same thing
print(three_d[1,0,-1])

3
[[[1 2 3]]]
1
1


In [37]:
# slicing
#[start:end:step]
arr= np.array([1,2,3,4,5,6,7,8,9,])
print(arr[2::2])
print(arr[2:])

[3 5 7 9]
[3 4 5 6 7 8 9]


In [38]:
# 2d slicing

arr = np.array([
    [1, 2, 3],
    [6, 4, 7]
])

print(arr[1,::-1]) # reverse array 


[7 4 6]


In [39]:

arr = np.array([
    [1, 2, 3, 4, 5], [6, 7, 8, 9, 10]
])


print(arr[0:2, 1:4])

display(arr[:, 2:])

[[2 3 4]
 [7 8 9]]


array([[ 3,  4,  5],
       [ 8,  9, 10]])

## Below is a list of all data types in NumPy and the characters used to represent them.

- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )


In [40]:
# check data type

arr=np.array([1,2,3,4,5,6,7])
arr_2=np.array(['c','s','w'])
display(arr.dtype)
display(arr_2.dtype)

dtype('int32')

dtype('<U1')

In [41]:
#create array with defined data type

arr = np.array([1,2,3,4] ,dtype='S')

display(arr.dtype)
display(arr)
sum =arr[1]+arr[2]
display(sum)

dtype('S1')

array([b'1', b'2', b'3', b'4'], dtype='|S1')

b'23'

## For i, u, f, S and U we can define size as well.



In [42]:
#Create an array with data type 4 bytes integer:

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [43]:
# convert data type of array 

arr = np.array([1.1, 2.1, 3.1]) # float arr
int_arr= arr.astype('i')
display(arr.dtype)
display(int_arr.dtype)
display(int_arr)



dtype('float64')

dtype('int32')

array([1, 2, 3], dtype=int32)

In [44]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


## NumPy Array Copy vs View


In [45]:
#copy
arr = np.array([1, 0, 3])

cp= arr.copy()

arr[0]=99
print(arr)
print(cp)

[99  0  3]
[1 0 3]


In [46]:
arr = np.array([1, 2, 3, 4, 5])
vi = arr.view()
# vi[0] = 42
arr[0]=42

print(arr)
print(vi)

[42  2  3  4  5]
[42  2  3  4  5]


In [47]:
#Check if Array Owns its Data

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

element = arr.copy()
y = arr.view()

print(element.base)
print(y.base)

None
[1 2 3 4 5]


# NumPy Array Shape


In [48]:
# array shape 

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
# return tuple 
display(arr.shape)

(2, 4)

In [49]:
arr = np.array([1,2,3,4,5],ndmin=5)

print(arr)
print(arr.shape)

[[[[[1 2 3 4 5]]]]]
(1, 1, 1, 1, 5)


## NumPy Array Reshaping


In [50]:
# Convert the following 1-D array with 12 elements into a 2-D array.
# The outermost dimension will have 4 arrays, each with 3 elements:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr.reshape(3, 4)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
'''Convert the following 1-D array with 12 elements into a 3-D array.

The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:'''

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

arr.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [52]:
#reshape is make new view 
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

arr =arr.reshape(2, 3,2)

print(arr)
print(arr.base)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


## Unknown Dimension
You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

In [53]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr.reshape(2,2,-1)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [54]:
# flattening array 

arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.reshape(-1) # make it on dimension array 


array([1, 2, 3, 4, 5, 6])

In [55]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for element in arr:
  for y in element:
    print(y)

1
2
3
4
5
6


In [56]:
#

arr = np.array([
    [
        [1, 2], [3, 4]
    ],
    [
        [5, 6], [7, 8]
    ]
])
print("by using nested loop :") 
for element in arr:
    for i in element :
        for j in i:
            print(j)
            
print("by using nditer function :") 
for element in np.nditer(arr):
    print(element)

by using nested loop :
1
2
3
4
5
6
7
8
by using nditer function :
1
2
3
4
5
6
7
8


In [57]:
arr = np.array([1, 2, 3])

for element in np.nditer(arr,op_dtypes=['S'],flags=['buffered']) :
    
    print(element)

b'1'
b'2'
b'3'


In [58]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for element in np.nditer(arr[:,::2]):
    print(element)

1
3
5
7


In [59]:
arr = np.array([1, 2, 3])

for index, element in np.ndenumerate(arr):
  print(index, element)

(0,) 1
(1,) 2
(2,) 3


In [60]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for index, element in np.ndenumerate(arr): 
  print(index, element)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [67]:
# join arrays

arr1 = np.array([1, 2, 3, 4, 5, 6])
arr2 = np.array([9, 8, 7, 6, 5, 4])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6 9 8 7 6 5 4]


In [69]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1,arr2),axis=1)
arr0 = np.concatenate((arr1,arr2),axis=0)
print(arr)
print('___________')
print(arr0)

[[1 2 5 6]
 [3 4 7 8]]
___________
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [82]:
arr1 = np.array([
    [
        [1, 2, 3, 4], [4, 2, 535, 12176]
    ],
    [
        [22, 44, 67, 77], [88, 55, 33, 22]
    ]
])
arr2 = np.array([
    [
        [12312, 46567, 643, 144], [99,77, 5095, 222]
    ],
    [
        [2112, 45674, 61227, 5577], [6588, 38955, 2733, 2642]
    ]
])

arr= np.concatenate((arr1,arr2),axis=2)
print('shape of one of base array :',arr1.shape)
print( arr)
print('______')
# concatenate return a copy not a view
print('base :' ,arr.base)


shape of one of base array : (2, 2, 4)
[[[    1     2     3     4 12312 46567   643   144]
  [    4     2   535 12176    99    77  5095   222]]

 [[   22    44    67    77  2112 45674 61227  5577]
  [   88    55    33    22  6588 38955  2733  2642]]]
______
base : None


In [88]:
# Joining Arrays Using Stack Functions

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

# we can not concatenate on new axis
# arr = np.concatenate((arr1,arr2),axis=1)

# stack allow to join tow array along new axis
# this code converts these tow one-dimensional arrays to one tow dimensional array
arr = np.stack((arr1, arr2), axis=1)


print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [94]:
# example : convert given arrays to 4dimensional array

arr1 = np.array([
    [
        [1, 2, 3, 4], [4, 2, 535, 12176]
    ],
    [
        [22, 44, 67, 77], [88, 55, 33, 22]
    ]
])
arr2 = np.array([
    [
        [12312, 46567, 643, 144], [99, 77, 5095, 222]
    ],
    [
        [2112, 45674, 61227, 5577], [6588, 38955, 2733, 2642]
    ]
])

arr = np.stack((arr1, arr2), axis=2)
print(arr,'\n ' ,arr.shape)


[[[[    1     2     3     4]
   [12312 46567   643   144]]

  [[    4     2   535 12176]
   [   99    77  5095   222]]]


 [[[   22    44    67    77]
   [ 2112 45674 61227  5577]]

  [[   88    55    33    22]
   [ 6588 38955  2733  2642]]]] 
  (2, 2, 2, 4)


In [95]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [96]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [97]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


## split arrays 

In [100]:
arr = np.array([1, 2, 3, 4, 5, 6])

arr=np.array_split(arr,3)
print(arr)
arr[1]

[array([1, 2]), array([3, 4]), array([5, 6])]


array([3, 4])

In [101]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [104]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)
# return 2d array
newarr[0]

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


array([[1, 2],
       [3, 4]])

In [106]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [
               10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)
newarr[0]

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


array([[1, 2, 3],
       [4, 5, 6]])

In [108]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [
               10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [111]:

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [
               10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [112]:
# search 
arr = np.array([1, 2, 3, 4, 5, 4, 4])
np.where(arr==4)


(array([3, 5, 6], dtype=int64),)

In [113]:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr % 2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [118]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)


x = np.searchsorted(arr, 7, side='right')

print(x)

1
2


In [119]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


## sorting 

In [120]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [121]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [122]:

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [123]:

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [124]:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]
